Remove set_marigin_start() call
This seems to fail to compile on some systems with:
 Compiling torrent-search v0.1.0 (file:///media/Daten/Eigene_Dateien/Programmieren/rust/rust-torrent-search)
 src/bin/torrent-search-gtk.rs:42:23: 42:42 error: no method named `set_margin_start` found for type `gtk::widgets::link_button::LinkButton` in the current scope
 src/bin/torrent-search-gtk.rs:42 title_and_url.set_margin_start(0);
 ^~~~~~~~~~~~~~~~~~~
 error: aborting due to previous error
 Build failed, waiting for other jobs to finish...
 Could not compile `torrent-search`.

Since it doesn't do anything meaningful we can just remove it.